# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JiFMD1540lK5cnbrOfO8U32XWLlbr1Tj
"""

from google.colab import drive

drive.mount('/content/drive/')

project_path='/content/drive/My Drive/Colab Notebooks/databases/datasets-master/Omniglot Dataset/'

training_path=project_path+'images_background-2.zip'
val_path=project_path + 'images_evaluation-2.zip'

from zipfile import ZipFile

with ZipFile(training_path,'r') as z:
  z.extractall()

from zipfile import ZipFile

with ZipFile(val_path,'r') as x:
  x.extractall()

